"use client";

import { useMemo, useState } from "react";
import { email } from "@/lib/data";
import { useStore } from "@/lib/store";

const STEPS = ["what", "features", "scope", "budget", "timeline", "brief"] as const;

const WHAT = ["Landing page", "Marketing website", "SaaS product", "Dashboard", "Something else"];
const FEATURES = ["CMS / editable content", "Auth & accounts", "Payments / billing", "Dashboard & charts", "AI features", "Integrations / API", "Automation", "Not sure yet"];
const SCOPE = ["Design + development", "Development only (design exists)", "Design only"];
const BUDGET = ["under $3k", "$3k – $8k", "$8k – $20k", "$20k+", "let's talk"];
const TIMELINE = ["ASAP", "within a month", "1–3 months", "flexible"];

export default function Planner() {
  const s = useStore();
  const [step, setStep] = useState(0);
  const [what, setWhat] = useState("");
  const [features, setFeatures] = useState<string[]>([]);
  const [scope, setScope] = useState("");
  const [budget, setBudget] = useState("");
  const [timeline, setTimeline] = useState("");
  const [notes, setNotes] = useState("");

  const brief = useMemo(() => {
    return [
      "PROJECT BRIEF — generated by stacksimo os",
      "",
      `Building:   ${what || "—"}`,
      `Features:   ${features.length ? features.join(", ") : "—"}`,
      `Scope:      ${scope || "—"}`,
      `Budget:     ${budget || "—"}`,
      `Timeline:   ${timeline || "—"}`,
      notes ? `Notes:      ${notes}` : "",
      "",
      "Next step: I reply within 24h with questions and a rough plan.",
    ]
      .filter(Boolean)
      .join("\n");
  }, [what, features, scope, budget, timeline, notes]);

  const mailto = `mailto:${email}?subject=${encodeURIComponent(`Project inquiry — ${what || "new project"}`)}&body=${encodeURIComponent(brief)}`;

  const canNext = [what, features.length > 0, scope, budget, timeline][step];

  const Choice = ({ options, value, onPick, multi = false }: { options: string[]; value: string | string[]; onPick: (v: string) => void; multi?: boolean }) => (
    <div className="choice-grid">
      {options.map((o) => {
        const on = multi ? (value as string[]).includes(o) : value === o;
        return (
          <button key={o} className={`choice ${on ? "on" : ""}`} onClick={() => onPick(o)} aria-pressed={on}>
            {o}
          </button>
        );
      })}
    </div>
  );

  return (
    <div className="planner">
      <h1 className="pane-title">Plan a project</h1>
      <p className="pane-sub">Five quick choices. It writes the brief for you — no blank-page contact form.</p>

      <div className="planner-progress" aria-hidden>
        {STEPS.map((st, i) => (
          <i key={st} className={i <= step ? "done" : ""} />
        ))}
      </div>

      {step === 0 && (
        <section>
          <h3>What are we building?</h3>
          <Choice options={WHAT} value={what} onPick={setWhat} />
        </section>
      )}
      {step === 1 && (
        <section>
          <h3>What does it need?</h3>
          <Choice options={FEATURES} value={features} multi onPick={(v) => setFeatures((f) => (f.includes(v) ? f.filter((x) => x !== v) : [...f, v]))} />
        </section>
      )}
      {step === 2 && (
        <section>
          <h3>What do you need from me?</h3>
          <Choice options={SCOPE} value={scope} onPick={setScope} />
        </section>
      )}
      {step === 3 && (
        <section>
          <h3>Rough budget?</h3>
          <Choice options={BUDGET} value={budget} onPick={setBudget} />
          <p className="pane-sub" style={{ marginTop: 14, fontSize: 12 }}>Honest ranges get honest answers. Fixed quotes always.</p>
        </section>
      )}
      {step === 4 && (
        <section>
          <h3>Timeline?</h3>
          <Choice options={TIMELINE} value={timeline} onPick={setTimeline} />
          <label className="mono" style={{ display: "block", marginTop: 18, fontSize: 11, color: "var(--muted)" }}>
            anything else? (optional)
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              placeholder="links, context, weird constraints…"
              style={{
                display: "block",
                width: "100%",
                marginTop: 8,
                background: "var(--surface)",
                border: "1px solid var(--hairline)",
                borderRadius: 9,
                padding: 12,
                color: "var(--ink)",
                font: "13px var(--font-ui), sans-serif",
                resize: "vertical",
              }}
            />
          </label>
        </section>
      )}
      {step === 5 && (
        <section>
          <h3>Your brief</h3>
          <pre className="brief">{brief}</pre>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            <a className="btn-primary" href={mailto} onClick={() => s.achieve("planner", "sent a project brief")}>
              Send it → {email}
            </a>
            <button
              className="escape-hatch"
              onClick={() => {
                navigator.clipboard.writeText(brief).then(() => s.toast("brief copied"));
              }}
            >
              copy brief
            </button>
          </div>
        </section>
      )}

      <div className="planner-nav">
        {step > 0 && (
          <button className="escape-hatch" onClick={() => setStep(step - 1)}>
            ← back
          </button>
        )}
        {step < 5 && (
          <button className="btn-primary" disabled={!canNext} onClick={() => setStep(step + 1)}>
            {step === 4 ? "Generate brief →" : "Next →"}
          </button>
        )}
      </div>

      <MessageForm />
    </div>
  );
}

function MessageForm() {
  const s = useStore();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [from, setFrom] = useState("");
  const [msg, setMsg] = useState("");

  const field: React.CSSProperties = {
    display: "block",
    width: "100%",
    marginTop: 6,
    background: "var(--surface)",
    border: "1px solid var(--hairline)",
    borderRadius: 9,
    padding: 12,
    color: "var(--ink)",
    font: "13px var(--font-ui), sans-serif",
  };
  const lbl: React.CSSProperties = { display: "block", marginTop: 14, fontSize: 11, color: "var(--muted)" };

  const body = `From: ${name || "—"}${from ? ` <${from}>` : ""}\n\n${msg}`;
  const mailto = `mailto:${email}?subject=${encodeURIComponent(`Message from ${name || "your website"}`)}&body=${encodeURIComponent(body)}`;

  return (
    <section style={{ marginTop: 40, paddingTop: 24, borderTop: "1px solid var(--hairline)" }}>
      {!open ? (
        <p className="pane-sub" style={{ fontSize: 13 }}>
          Prefer to just write?{" "}
          <button className="escape-hatch" onClick={() => setOpen(true)}>
            send a plain message →
          </button>
        </p>
      ) : (
        <div style={{ maxWidth: 480 }}>
          <h3>Send a message</h3>
          <label className="mono" style={lbl}>
            your name
            <input style={field} value={name} onChange={(e) => setName(e.target.value)} placeholder="Jane Doe" />
          </label>
          <label className="mono" style={lbl}>
            your email
            <input style={field} type="email" value={from} onChange={(e) => setFrom(e.target.value)} placeholder="jane@company.com" />
          </label>
          <label className="mono" style={lbl}>
            message
            <textarea style={{ ...field, resize: "vertical" }} rows={4} value={msg} onChange={(e) => setMsg(e.target.value)} placeholder="tell me about your project…" />
          </label>
          <div style={{ display: "flex", gap: 12, marginTop: 16 }}>
            <a
              className="btn-primary"
              href={mailto}
              onClick={() => s.toast("opening your email app…")}
              aria-disabled={!msg}
              style={!msg ? { opacity: 0.5, pointerEvents: "none" } : undefined}
            >
              Send → {email}
            </a>
            <button className="escape-hatch" onClick={() => setOpen(false)}>
              never mind
            </button>
          </div>
        </div>
      )}
    </section>
  );
}
